#!/bin/bash
# Auto-detect displays and generate sway output config
# Run this once on a new machine: ./setup-displays.sh
# It will create ~/.config/sway/displays.conf which is sourced by the main config

DISPLAYS_CONF="$HOME/.config/sway/displays.conf"

# Safety: restore all displays to full brightness on exit/interrupt
restore_all_brightness() {
    for o in $(swaymsg -t get_outputs 2>/dev/null | jq -r '.[] | select(.active==true) | .name'); do
        swaymsg "output $o brightness 1" 2>/dev/null
    done
}
trap restore_all_brightness EXIT INT TERM

# Flash a display to identify it — dims it briefly then restores
identify_display() {
    local output="$1"
    echo "  >>> Dimming '$output' for 2 seconds..."
    swaymsg "output $output brightness 0.1"
    sleep 2
    swaymsg "output $output brightness 1"
}

echo "=== Display Setup ==="
echo ""

# Get connected outputs
outputs=$(swaymsg -t get_outputs 2>/dev/null | jq -r '.[] | select(.active==true) | .name')

if [ -z "$outputs" ]; then
    echo "No active displays detected. Make sure sway is running."
    exit 1
fi

echo "Active displays:"
swaymsg -t get_outputs | jq -r '.[] | select(.active==true) | "  \(.name): \(.current_mode.width)x\(.current_mode.height)@\(.current_mode.refresh/1000)Hz"'
echo ""

count=$(echo "$outputs" | wc -l)

# Identify each display by dimming it
echo "Identifying displays..."
echo ""
for output in $outputs; do
    identify_display "$output"
    echo ""
done

if [ "$count" -eq 1 ]; then
    main=$(echo "$outputs" | head -1)
    echo "# Single monitor setup" > "$DISPLAYS_CONF"
    echo "# Generated by setup-displays.sh on $(date)" >> "$DISPLAYS_CONF"
    echo "" >> "$DISPLAYS_CONF"
    echo "# Main monitor" >> "$DISPLAYS_CONF"
    for ws in $(seq 1 10); do
        echo "workspace $ws output $main" >> "$DISPLAYS_CONF"
    done
    echo ""
    echo "Single monitor detected: $main"

elif [ "$count" -ge 2 ]; then
    echo "Now let's pick your monitors."
    echo "I'll dim a screen — tell me what role it has."
    echo ""

    declare -A roles
    remaining_outputs=($outputs)

    # Identify main monitor
    for output in "${remaining_outputs[@]}"; do
        identify_display "$output"
        read -p "  Is this your MAIN monitor? [y/N]: " answer
        if [[ "$answer" =~ ^[Yy]$ ]]; then
            main="$output"
            break
        fi
    done

    if [ -z "$main" ]; then
        echo "No main monitor selected. Aborting."
        exit 1
    fi

    # Identify secondary monitor
    secondary=""
    for output in $outputs; do
        [ "$output" = "$main" ] && continue
        identify_display "$output"
        read -p "  Use this as your SECONDARY monitor? [y/N]: " answer
        if [[ "$answer" =~ ^[Yy]$ ]]; then
            secondary="$output"
            break
        fi
    done

    echo ""
    echo "Main: $main"
    [ -n "$secondary" ] && echo "Secondary: $secondary"
    echo ""

    # Write config
    echo "# Dual monitor setup" > "$DISPLAYS_CONF"
    echo "# Generated by setup-displays.sh on $(date)" >> "$DISPLAYS_CONF"
    echo "" >> "$DISPLAYS_CONF"

    if [ -n "$secondary" ]; then
        read -p "Is the secondary monitor rotated/portrait? [y/N]: " rotated
        if [[ "$rotated" =~ ^[Yy]$ ]]; then
            echo "# Secondary (portrait, left)" >> "$DISPLAYS_CONF"
            echo "output $secondary transform 270" >> "$DISPLAYS_CONF"
            echo "output $secondary pos 0 0" >> "$DISPLAYS_CONF"
            echo "output $main pos 1080 0" >> "$DISPLAYS_CONF"
        else
            echo "# Secondary (landscape, left)" >> "$DISPLAYS_CONF"
            echo "output $secondary pos 0 0" >> "$DISPLAYS_CONF"
            echo "output $main pos 1920 0" >> "$DISPLAYS_CONF"
        fi

        echo "" >> "$DISPLAYS_CONF"
        echo "# Main monitor gets 1-5" >> "$DISPLAYS_CONF"
        for ws in 1 2 3 4 5; do
            echo "workspace $ws output $main" >> "$DISPLAYS_CONF"
        done
        echo "# Secondary monitor gets 6-10" >> "$DISPLAYS_CONF"
        for ws in 6 7 8 9 10; do
            echo "workspace $ws output $secondary" >> "$DISPLAYS_CONF"
        done
    else
        echo "# Main monitor" >> "$DISPLAYS_CONF"
        for ws in $(seq 1 10); do
            echo "workspace $ws output $main" >> "$DISPLAYS_CONF"
        done
    fi

    # Disable laptop display if present and not selected
    for output in $outputs; do
        if [[ "$output" == eDP-* ]] && [[ "$output" != "$main" ]] && [[ "$output" != "$secondary" ]]; then
            echo "" >> "$DISPLAYS_CONF"
            echo "# Laptop display disabled (lid closed)" >> "$DISPLAYS_CONF"
            echo "output $output disable" >> "$DISPLAYS_CONF"
        fi
    done
fi

echo ""
echo "Config written to $DISPLAYS_CONF"
echo "Reload sway with \$mod+Shift+c to apply."
